#!/usr/bin/env python3
"""Translate batch 9 large EN bodies via headings + paragraph pairs."""
from __future__ import annotations

import re
from pathlib import Path

BODY = Path(__file__).resolve().parent / "_batch9_bodies"

SLUGS = [
    "appdev-quickstart-deploy-to-devnet",
    "appdev-quickstart-running-the-demo",
    "appdev-quickstart-observability-and-tracing",
    "appdev-quickstart-json-api",
]


def apply(en: str, title_zh: str, sub_zh: str, headings: dict, pairs: list) -> str:
    en = re.sub(r"^# [^\n]+\n\n# [^\n]+\n\n", f"# {title_zh}\n\n# {sub_zh}\n\n", en, count=1)
    for k, v in headings.items():
        en = en.replace(k, v)
    for a, b in sorted(pairs, key=lambda x: -len(x[0])):
        en = en.replace(a, b)
    return en


COMMON = [
    ("<Note>", "<Note>"),
    ("<Warning>", "<Warning>"),
    ("<Tip>", "<Tip>"),
    ("<div class=\"tip\" markdown=\"1\">", "<div class=\"tip\" markdown=\"1\">"),
    ("<div class=\"note\" markdown=\"1\">", "<div class=\"note\" markdown=\"1\">"),
    ("    Tip", "    提示"),
    ("    Note", "    说明"),
    ("DevNet Host Entries", "DevNet 主机条目"),
]


def deploy():
    en = (BODY / "appdev-quickstart-deploy-to-devnet.en.txt").read_text()
    h = {
        "## Overview": "## 概览",
        "## DevNet validator prerequisite": "## DevNet 验证者前置条件",
        "## Architectural overview": "## 架构概览",
        "## Quickstart configuration for DevNet": "## Quickstart 的 DevNet 配置",
        "## Configure Host entries": "## 配置 Host 条目",
        "## Download the Splice node release bundle": "## 下载 Splice 节点发行包",
        "## Navigate to the validator's Docker Compose directory": "## 进入验证者 Docker Compose 目录",
        "## Connect to a Canton Network Validator Node": "## 连接 Canton Network 验证者节点",
        "### Mac OS": "### macOS",
        "### Linux": "### Linux",
        "## Clean Docker": "## 清理 Docker",
        "## Get network information": "## 获取网络信息",
        "### Retrieve DevNet migration ID and Splice version": "### 获取 DevNet migration ID 与 Splice 版本",
        "### Get the onboarding secret": "### 获取 onboarding secret",
        "### Party Hint": "### Party Hint",
        "## Authentication": "## 认证",
        "## Start the validator with the start.sh script.": "## 用 start.sh 启动验证者",
        "### Flag descriptions": "### 参数说明",
        "## Spin up the Quickstart DevNet": "## 启动 Quickstart DevNet",
        "## Build and upload the DAR": "## 构建并上传 DAR",
        "## Upload the DAR to your DevNet validator": "## 向 DevNet 验证者上传 DAR",
        "### MacOS": "### macOS",
        "## Build the Backend": "## 构建后端",
        "## Configure Quickstart frontend for DevNet": "## 为 DevNet 配置 Quickstart 前端",
        "## Appendix": "## 附录",
        "### Recipes": "### 常用脚本",
        "#### Start and stop scripts": "#### 启停脚本",
        "#### Health check": "#### 健康检查",
        "#### Super validator connectivity check": "#### 超级验证者连通性检查",
        "#### View tables": "#### 查看表",
        "#### Confirm current migration ID": "#### 确认当前 migration ID",
        "#### Find DSO fingerprint": "#### 查找 DSO 指纹",
        "### Docker": "### Docker",
        "#### Read docker logs": "#### 查看 Docker 日志",
        "#### Kill running containers": "#### 强制结束容器",
        "#### Stop gracefully": "#### 优雅停止",
        "#### Remove containers after stopping": "#### 停止后删除容器",
        "#### One command": "#### 一条命令",
        "### Troubleshooting": "### 排障",
        "#### Resolve vmnetd errorIf you experience a `vmnetd` error response then the most": "#### 解决 vmnetd 错误\n\n若出现 `vmnetd` 错误，通常",
        "#### Troubleshoot frontend JavaScript mapping errors": "#### 排查前端 JavaScript 映射错误",
        "##### Switch BACKEND\\_PORT from 8080 to 8089": "##### 将 BACKEND_PORT 从 8080 改为 8089",
        "##### Update proxyReq in vite configuration": "##### 更新 vite 配置中的 proxyReq",
        "##### Ping app-provider.localhost": "##### ping app-provider.localhost",
        "##### Check backend-service logs for errors": "##### 检查 backend-service 日志",
        "##### Find the login options": "##### 查找登录选项",
        "##### Get token for backend API access": "##### 获取后端 API 访问令牌",
        "##### Verify token was retrieved": "##### 验证令牌已获取",
        "##### Query data from PQS": "##### 从 PQS 查询数据",
        "#### Error port is already in use": "#### 端口已被占用",
        "#### Restart unhealthy Docker containers": "#### 重启不健康的 Docker 容器",
        "#### Keycloak": "#### Keycloak",
        "#### Unable to login to Keycloak as admin": "#### 无法以 admin 登录 Keycloak",
        "#### Splice-onboarding troubleshooting": "#### splice-onboarding 排障",
        "#### Splice-onboarding connection issue": "#### splice-onboarding 连接问题",
    }
    p = [
        ("In this guide, you'll deploy the Quickstart app from LocalNet to DevNet. You'll deploy the original DAR, deploy to the backend, frontend and test the workflow.",
         "本指南将 Quickstart 应用从 LocalNet 部署到 DevNet：部署原始 DAR、后端与前端并测试工作流。"),
        ("You should have the Quickstart application *installed* and understand the `quickstart-project-structure-guide`.",
         "你应已*安装* Quickstart 并理解 `quickstart-project-structure-guide`。"),
        ("You must have successfully submitted a validator request to successfully complete this guide.",
         "须已成功提交验证者申请才能完成本指南。"),
        ("Submit your request at:", "在此提交申请："),
        ("Visit the global synchronizer docs to learn more about the validator onboarding process and how to deploy a validator with Docker Compose.",
         "全局 synchronizer 文档介绍验证者接入流程及用 Docker Compose 部署验证者。"),
        ("You can find up-to-date Canton Foundation DevNet Super Validator Node Information at:",
         "Canton Foundation DevNet 超级验证者节点最新信息："),
        ("The Quickstart DevNet deployment splits across two components:", "Quickstart DevNet 部署分两部分："),
        ("* **splice-node**: Provides the validator infrastructure (participant, validator, wallet-ui, ans-ui)",
         "* **splice-node**：验证者基础设施（participant、validator、wallet-ui、ans-ui）"),
        ("* **cn-quickstart**: Provides the application layer (keycloak, pqs, backend-service, frontend)",
         "* **cn-quickstart**：应用层（keycloak、pqs、backend-service、frontend）"),
        ("`splice-node` ports are internal container ports and routed via nginx by hostname. `cn-quickstart` ports are directly exposed.",
         "`splice-node` 端口为容器内部端口，经 nginx 按主机名路由；`cn-quickstart` 端口直接暴露。"),
        ("The frontend communicates with the backend via HTTP REST calls to `/api/*` endpoints. The Vite development server proxies these requests to the backend, which translates them into Ledger API calls. For a detailed explanation of this fully mediated architecture, see `quickstart-project-structure-guide`.",
         "前端经 HTTP REST 调用 `/api/*`；Vite 开发服务器将请求代理到后端，后端再转为 Ledger API 调用。完全中介架构详见 `quickstart-project-structure-guide`。"),
        ("Quickstart environment variables are set for `LocalNet` usage by default, but ledger connections differ between `LocalNet` and `DevNet` configurations. For example:",
         "Quickstart 环境变量默认为 `LocalNet`，但账本连接在 `LocalNet` 与 `DevNet` 间不同，例如："),
        ("| Variable      | LocalNet Value | DevNet Value                |", "| 变量 | LocalNet 值 | DevNet 值 |"),
        ("| `LEDGER_HOST` | `localhost`    | `grpc-ledger-api.localhost` |", "| `LEDGER_HOST` | `localhost` | `grpc-ledger-api.localhost` |"),
        ("| `LEDGER_PORT` | `5001`         | `80` or `8080`              |", "| `LEDGER_PORT` | `5001` | `80` 或 `8080` |"),
        ("`nginx.conf` uses virtual hosting to route requests to backend services. As a result, nginx inspects your `Host` HTTP header to determine backend routing. Add explicit host entires for reliable routing.",
         "`nginx.conf` 用虚拟主机路由；nginx 根据 `Host` 头选择后端，建议添加显式主机条目。"),
        ("Add these entries to `/etc/hosts`:", "在 `/etc/hosts` 添加："),
        ("You only need to complete this step one time.", "此步骤只需完成一次。"),
        ("| Host Entry                  | URL                                   | Purpose                                      |",
         "| 主机条目 | URL | 用途 |"),
        ("| `json-ledger-api.localhost` | `http://json-ledger-api.localhost/`   | JSON Ledger API (REST commands, DAR uploads) |",
         "| `json-ledger-api.localhost` | `http://json-ledger-api.localhost/` | JSON Ledger API（REST 命令、DAR 上传） |"),
        ("| `grpc-ledger-api.localhost` | `http://grpc-ledger-api.localhost/`   | gRPC Ledger API (backend's `LEDGER_HOST`)    |",
         "| `grpc-ledger-api.localhost` | `http://grpc-ledger-api.localhost/` | gRPC Ledger API（后端 `LEDGER_HOST`） |"),
        ("| `validator.localhost`       | `http://validator.localhost/`         | Validator application API                    |",
         "| `validator.localhost` | `http://validator.localhost/` | 验证者应用 API |"),
        ("| `wallet.localhost`          | `http://wallet.localhost/`            | Canton Wallet web interface                  |",
         "| `wallet.localhost` | `http://wallet.localhost/` | Canton 钱包 Web UI |"),
        ("| `app-provider.localhost`    | `http://app-provider.localhost:5173/` | Quickstart frontend web interface            |",
         "| `app-provider.localhost` | `http://app-provider.localhost:5173/` | Quickstart 前端 |"),
        ("| `participant.localhost`     | `http://participant.localhost/`       | Participant admin/metrics                    |",
         "| `participant.localhost` | `http://participant.localhost/` | Participant 管理/指标 |"),
        ("| `ans.localhost`             | `http://ans.localhost/`               | Canton Name Service (ANS) web interface      |",
         "| `ans.localhost` | `http://ans.localhost/` | Canton 名称服务（ANS） |"),
        ("| `keycloak.localhost`        | `http://keycloak.localhost:8082/`     | OAuth2/OIDC provider                         |",
         "| `keycloak.localhost` | `http://keycloak.localhost:8082/` | OAuth2/OIDC 提供方 |"),
        ("The nginx proxy routes based on hostname. Default port is 80. MacOS users may need to change the validator port from 80 to 8080 to avoid `vmnetd` errors. See `vmnetd-error` in the Troubleshooting section.",
         "nginx 按主机名路由，默认端口 80。macOS 用户可能需将验证者端口改为 8080 以避免 `vmnetd` 错误，见排障章节。"),
        ("In `DevNet`, your Splice node validator runs locally and connects to the `DevNet` synchronizer. Download and extract the Splice node bundle by following the Requirements step in the [Docker Compose Validator Deployment guide](/global-synchronizer/deployment/validator-docker-compose#requirements).",
         "在 `DevNet` 上 Splice 验证者本地运行并连接 `DevNet` synchronizer。按[ Docker Compose 验证者部署指南](/global-synchronizer/deployment/validator-docker-compose#requirements) 的 Requirements 下载并解压 Splice 节点包。"),
        ("The extracted `splice-node` directory and `cn-quickstart` should be siblings to one another:",
         "解压后的 `splice-node` 与 `cn-quickstart` 应为同级目录："),
        ("  Find the most recent Splice release on the [canton-network/splice releases page](https://github.com/canton-network/splice/releases).",
         "  最新 Splice 版本见 [canton-network/splice releases](https://github.com/canton-network/splice/releases)。"),
        ("Navigate to your OS's VPN settings, then connect to your sponsoring validator node.",
         "在系统 VPN 设置中连接赞助验证者节点。"),
        ("VPN access is required for `DevNet`. Contact your sponsoring SV for VPN credentials.",
         "访问 `DevNet` 需要 VPN；请联系赞助 SV 获取凭证。"),
        ("Settings > VPN", "设置 > VPN"),
        ("Enable your Canton Network VPN", "启用 Canton Network VPN"),
        ("Network > VPN", "网络 > VPN"),
        ("Clear Docker If this is not your first time connecting to `DevNet` so that stale containers do not interfere.",
         "若非首次连接 `DevNet`，请清理 Docker 以免陈旧容器干扰。"),
        ("In terminal, from the `/validator` directory run:", "在终端于 `/validator` 目录运行："),
        ("Verify that the Splice version matches the splice-node version that you recently downloaded and unzipped. Minor Splice versions change on a regular basis. You may elect to hard code `SPLICE_VERSION` rather than saving the most recent version, e.g. `SPLICE_VERSION=0.6.4`",
         "确认 Splice 版本与刚下载解压的 splice-node 一致。小版本常更新，可硬编码 `SPLICE_VERSION`，例如 `SPLICE_VERSION=0.6.4`。"),
        ("You may use the following Super Validator URL if you are connected to the Canton Network Global Synchronizer. If not, your sponsoring SV will provide the appropriate URL. In this case, you must replace the provided `SPONSOR_SV_URL` with your provided URL.",
         "若已连接 Global Synchronizer 可使用下列 SV URL；否则由赞助 SV 提供 URL，并替换 `SPONSOR_SV_URL`。"),
        ("  The onboarding secret is only good for 1 hour. If containers ever show unhealthy, try requesting a new onboarding secret as your first step in troubleshooting.",
         "  onboarding secret 仅 1 小时有效；容器不健康时首先尝试重新申请。"),
        ("Set a Party Hint. The party hint must match the expected hint that is established when running `make setup` from `cn-quickstart/quickstart`.",
         "设置 Party Hint，须与 `cn-quickstart/quickstart` 运行 `make setup` 时一致。"),
        ("If you don't remember your party hint, you can open a terminal and navigate to `cn-quickstart/quickstart/`, then run `make setup`.",
         "若忘记 party hint，在 `cn-quickstart/quickstart/` 运行 `make setup`。"),
        ("The default party hint is `quickstart-USERNAME-1`", "默认 party hint 为 `quickstart-USERNAME-1`"),
        ("Return to the terminal in the `validator` directory. Set `PARTY_HINT`.", "回到 `validator` 目录终端，设置 `PARTY_HINT`。"),
        ("This value must match the expected party hint.", "该值须与预期 party hint 一致。"),
        ("  If you would like to connect to `DevNet` without authentication, you may skip this section and initiate the `start.sh` script without the `-a` flag.",
         "  若无需认证连接 `DevNet`，可跳过本节并以不带 `-a` 的 `start.sh` 启动。"),
        ("Update authentication variables in `splice-node/docker-compose/validator/.env` using Quickstart's pre-configured Keycloak values. The following Authentication values can be found in `cn-quickstart`'s keycloak `env`, realm and user JSON files. Files include `quickstart/quickstart/docker/modules/keycloak/compose.env`, `AppProvider-realm.json`, and `AppProvider-users-0.json`.",
         "用 Quickstart 预置 Keycloak 值更新 `splice-node/docker-compose/validator/.env` 认证变量；见 `cn-quickstart` 的 compose.env、AppProvider-realm.json、AppProvider-users-0.json 等。"),
        ("  These are development secrets and should be changed for production.", "  此为开发密钥，生产环境须更换。"),
        ("Verify that you are in the `validator` directory, then run this command to connect to `DevNet`:",
         "确认位于 `validator` 目录后运行以下命令连接 `DevNet`："),
        ("| Flag | Description                                |", "| 参数 | 说明 |"),
        ("| `-s` | Sponsor SV URL                             |", "| `-s` | 赞助 SV URL |"),
        ("| `-o` | Onboarding secret                          |", "| `-o` | Onboarding secret |"),
        ("| `-p` | Your unique party hint                     |", "| `-p` | 你的 party hint |"),
        ("| `-m` | Migration ID (a non-negative integer)      |", "| `-m` | Migration ID（非负整数） |"),
        ("| `-w` | Wait for validator to be fully operational |", "| `-w` | 等待验证者完全就绪 |"),
        ("| `-a` | Enable authentication                      |", "| `-a` | 启用认证 |"),
        ("  You can omit the `-a` flag to skip authentication setup. This may make initial testing easier, but you should enable authentication for production use.",
         "  可省略 `-a` 跳过认证以便初测，生产应启用认证。"),
        ("While `DevNet` is starting, move on to the next step. (You'll need to complete the next step before `DevNet` is able to connect).",
         "`DevNet` 启动时可进行下一步（须在连接成功前完成下一步）。"),
        ("In a second terminal, navigate to the Quickstart `DevNet` Docker Compose directory.",
         "在第二终端进入 Quickstart `DevNet` Docker Compose 目录。"),
        ("`DevNet` connects shortly after spinning up the docker containers. A successful connection shows healthy containers.",
         "启动容器后 `DevNet` 将连接；成功时容器为 healthy。"),
        ("  See the Troubleshooting section if you experience a `vmnetd` error.", "  若遇 `vmnetd` 错误见排障章节。"),
        ("Return to the `/quickstart` directory.", "回到 `/quickstart` 目录。"),
        ("Then build the Daml code.", "然后构建 Daml。"),
        ("Verify that the `DAR` was created.", "确认 `DAR` 已生成。"),
        ("If successful, this command returns the `DAR` file.", "成功则返回 `DAR` 文件。"),
        ("Get a token from Keycloak to make an authenticated request:", "从 Keycloak 获取令牌以进行认证请求："),
        ("(Note that the `client_secret` matches the `app-provider-validator`'s `secret` in Keycloak's `AppProvider-realm.json`).",
         "（`client_secret` 与 Keycloak `AppProvider-realm.json` 中 `app-provider-validator` 的 `secret` 一致。）"),
        ("From the `/quickstart` directory, upload the `DAR` to your `DevNet` validator (MacOS users replace `${LEDGER_PORT}` with `8080`):",
         "在 `/quickstart` 向 `DevNet` 验证者上传 `DAR`（macOS 将 `${LEDGER_PORT}` 换为 `8080`）："),
        ("An empty response of `{}` indicates a successful upload.", "空响应 `{}` 表示上传成功。"),
        ("Build the backend from the `/quickstart` directory:", "在 `/quickstart` 构建后端："),
        ("The frontend communicates with the backend via HTTP REST calls to `/api/*` endpoints. The Vite development server proxies these requests to the backend, which translates them into Ledger API calls to the `DevNet` participant. Review `vite.config.ts` for details.",
         "前端经 `/api/*` REST 与后端通信；Vite 代理到后端，后端再调用 `DevNet` participant 的 Ledger API。详见 `vite.config.ts`。"),
        ("Build the frontend from the `/quickstart` directory:", "在 `/quickstart` 构建前端："),
        ("Start the Vite development server.", "启动 Vite 开发服务器。"),
        ("The frontend runs on `port 5173`. Open your browser to:", "前端运行于端口 `5173`，浏览器打开："),
        ("It's extremely important to prepend `localhost` with `app-provider` in order to successfully log in through Keycloak.",
         "通过 Keycloak 登录须在 `localhost` 前加 `app-provider` 主机名。"),
        ("Select AppProvider", "选择 AppProvider"),
        ("Login as `app-provider` with password `abc123`", "以 `app-provider` / 密码 `abc123` 登录"),
        ("You sign in to the App Provider's Quickstart homepage. Congratulations! You've launched Quickstart to `DevNet`!",
         "你已登录应用提供方 Quickstart 首页。恭喜，Quickstart 已部署到 `DevNet`！"),
        ("  Quickstart won't immediately operate as it does on `LocalNet`. You'll need to refactor to resolve connectivity issues. Perhaps begin with `make create-app-install-request`.",
         "  Quickstart 在 `DevNet` 上不会立刻与 `LocalNet` 相同，需调整连通性；可从 `make create-app-install-request` 开始。"),
        ("In the future, use the provided `start.sh` and `stop.sh` scripts to quickly start and stop Quickstart `DevNet` Docker containers.",
         "日后可用 `start.sh`/`stop.sh` 快速启停 Quickstart `DevNet` 容器。"),
        ("Use `./start.sh` to run a live log stream in terminal. (exit with ctrl+c) Opt for `./start.sh -d` to spin up the containers without a log stream.",
         "`./start.sh` 在终端显示实时日志（Ctrl+C 退出）；`./start.sh -d` 无日志流启动。"),
        ("Stop all of the Quickstart `DevNet` Docker containers with `./stop.sh`. You may also remove the volumes with `./stop.sh -v`.",
         "用 `./stop.sh` 停止容器；`./stop.sh -v` 可删除卷。"),
        ("You can check that Docker services are connected by checking `docker ps`. To check a specific service use grep. e.g. `docker ps | grep backend-service`.",
         "用 `docker ps` 检查服务；例如 `docker ps | grep backend-service`。"),
        ("Via, CURL, get a token and then ping the service.", "用 curl 获取令牌后探测服务。"),
        ("Get an auth token:", "获取认证令牌："),
        ("Call the service of your choice:", "调用所选服务："),
        ("You may make a connectivity check to the `DevNet` super validator at anytime:",
         "可随时检查与 `DevNet` 超级验证者的连通性："),
        ("You can explore the container schema by querying the list of tables.",
         "可查询表列表探索容器 schema。"),
        ("straightforward solution is to update the validator compose port from 80 to 8080.",
         "最直接做法是将验证者 compose 端口从 80 改为 8080。"),
        ("If necessary, to resolve \"vmnetd running errors\", find `nginx` service in `splice-node/docker-compose/validator/compose.yaml`. It is currently at line 163. Change port `80:80` in `\"${HOST_BIND_IP:-127.0.0.1}:80:80\"` to `8080:80`.",
         "若需解决 vmnetd 错误，在 `compose.yaml` 找到 nginx（约第 163 行），将 `80:80` 改为 `8080:80`。"),
        ("Open `cn-quickstart/quickstart/.env` in a text editor and change `BACKEND_PORT=8080` to `BACKEND_PORT=8089`.",
         "编辑 `cn-quickstart/quickstart/.env`，将 `BACKEND_PORT=8080` 改为 `8089`。"),
        ("Change line 35 in `vite.config.ts` from `proxyReq.setHeader('host', 'app-provider.localhost')` to `proxyReq.setHeader('host', 'app-provider.localhost:5173')`.",
         "将 `vite.config.ts` 第 35 行 host 改为 `app-provider.localhost:5173`。"),
        ("If successful, navigate to the app at [http://app-provider.localhost:5173](http://app-provider.localhost:5173) and login.",
         "成功后访问 [http://app-provider.localhost:5173](http://app-provider.localhost:5173) 并登录。"),
        ("Query app install requests", "查询 app install 请求"),
        ("Query license data", "查询许可数据"),
        ("If terminal shows `Error: Port 5173 is already in use` identify and kill the associated node process, then run your command again.",
         "若提示端口 5173 被占用，查找并结束 node 进程后重试。"),
        ("If you have trouble connecting to healthy containers, restart the Docker containers and capture full logs.",
         "若无法连接 healthy 容器，重启并捕获完整日志。"),
        ("Stop the container", "停止容器"),
        ("Start fresh and capture the logs", "重新启动并捕获日志"),
        ("Read logs in terminal:", "在终端阅读日志："),
        ("Replace `splice-validator-validator-1` with the desired container.", "将容器名替换为实际名称。"),
        ("  You can login to the Keycloak admin GUI at `http://host.docker.internal:8082/` Use `admin` for the username and password.",
         "  Keycloak 管理 GUI：`http://host.docker.internal:8082/`，用户名/密码均为 `admin`。"),
        ("Check Keycloak logs:", "查看 Keycloak 日志："),
        ("Check PostgreSQL:", "查看 PostgreSQL："),
        ("Check the OIDC discovery endpoint:", "检查 OIDC discovery 端点："),
        ("Get an OAuth2 `AppProvider realm` token:", "获取 OAuth2 `AppProvider realm` 令牌："),
        ("Get an OAuth2 `AppUser realm` token:", "获取 OAuth2 `AppUser realm` 令牌："),
        ("Check Keycloak's public key location:", "检查 Keycloak 公钥位置："),
        ("Expected response is `\"http://host.docker.internal:8082/realms/AppProvider\"`",
         "预期为 `\"http://host.docker.internal:8082/realms/AppProvider\"`"),
        ("The following command disables the SSL requirements for the master realm and allows you to login as admin at `localhost:8082`.",
         "下列命令禁用 master realm 的 SSL 要求，以便在 `localhost:8082` 以 admin 登录。"),
        ("Find specific env values:", "查找特定 env 值："),
        ("Restart the `splice-onboarding` container:", "重启 `splice-onboarding` 容器："),
        ("Watch the logs:", "查看日志："),
        ("Query `splice-onboarding` networks:", "查询 `splice-onboarding` 网络："),
        ("Check which network the `splice-validator-nginx` is on:", "检查 `splice-validator-nginx` 所在网络："),
        ("Then inspect that container to see its network:", "再检查该容器网络："),
        ("Check if `splice-onboarding` is initialized:", "检查 `splice-onboarding` 是否已初始化："),
        ("If you run `splice-onboarding` logs and see:", "若 `splice-onboarding` 日志显示："),
        ("Then there is likely an error in `LEDGER_HOST` or `LEDGER_PORT`. Unset the variables or quit and restart terminal.",
         "则 `LEDGER_HOST` 或 `LEDGER_PORT` 可能有误；取消设置变量或重启终端。"),
        ("# Authentication", "# 认证"),
        ("# Admin users ", "# 管理用户 "),
    ]
    p.extend(COMMON)
    out = apply(en, "部署 Quickstart 到 DevNet", "部署 Quickstart 到 DevNet", h, p)
    (BODY / "appdev-quickstart-deploy-to-devnet.zh.txt").write_text(out, encoding="utf-8")
    print("deploy", len(out))


def running_demo():
    en = (BODY / "appdev-quickstart-running-the-demo.en.txt").read_text()
    h = {
        "## Business case": "## 业务场景",
        "### Core business operations": "### 核心业务操作",
        "#### Issuing a license": "#### 签发许可",
        "#### Requesting a license renewal": "#### 请求许可续期",
        "#### Paying for a license renewal": "#### 支付许可续期",
        "#### Renewing the license": "#### 续期许可",
        "## Overview": "## 概览",
        "## Prerequisites": "## 前置条件",
        "## Walkthrough": "## 演练",
        "### Build Quickstart": "### 构建 Quickstart",
        "### Login": "### 登录",
        "### The App Installs Menu": "### 应用安装菜单",
        "### AppInstallRequest": "### AppInstallRequest",
        "### Create a license": "### 创建许可",
        "### Make a payment": "### 付款",
        "### Renew the license": "### 续期许可",
        "## Canton Console": "## Canton Console",
        "## Daml Shell": "## Daml Shell",
        "## Canton Coin Scan": "## Canton Coin Scan",
        "## Observability Dashboard": "## 可观测性仪表板",
        "## SV UIs": "## SV UI",
        "## Next steps": "## 下一步",
    }
    p = [
        ("The Canton Network (CN) Quickstart is scaffolding to support development efforts to build, test, and deploy CN applications. It resolves infrastructure problems that every CN application must solve. Use the CN Quickstart Application so you and your team can focus on building your application, instead of build systems, deployment configurations, and testing infrastructure.",
         "CN Quickstart 是构建、测试与部署 CN 应用的脚手架，解决每个 CN 应用都需处理的基础设施问题，让团队专注业务而非构建系统、部署与测试基础设施。"),
        ("The Quickstart features a sample licensing app to demonstrate Canton development patterns. In the app, providers sell time-based access to their services. Users pay with Canton Coin (CC) and manage payments through a Canton Wallet.",
         "Quickstart 以示例许可应用演示 Canton 开发模式：提供方销售基于时间的服务访问，用户用 Canton Coin（CC）并通过 Canton 钱包管理支付。"),
        ("* The **Application Provider** who sells licenses.", "* **应用提供方**销售许可。"),
        ("* The **Application User** who buys licenses.", "* **应用用户**购买许可。"),
        ("* The underlying **Amulet** token system that handles payments, using [CC](https://www.canton.network/blog/canton-coin-a-canton-network-native-payment-application).",
         "* 底层 **Amulet** 代币系统处理支付，使用 [CC](https://www.canton.network/blog/canton-coin-a-canton-network-native-payment-application)。"),
        ("* The **DSO Party**, the Decentralized Synchronizer Operations Party who operates the Amulet payment system. In CN, this is the Super Validators.",
         "* **DSO Party**（去中心化 Synchronizer 运营方）运营 Amulet 支付系统；在 CN 中为 Super Validator。"),
        ("The provider creates a new license for an onboarded user. The license starts expired and needs to be renewed before use.",
         "提供方为已入驻用户创建新许可；许可初始为过期，使用前须续期。"),
        ("The provider creates a renewal request, generating a payment request for the user. A matching CC payment request is created on the ledger.",
         "提供方创建续期请求并为用户生成付款请求；账本上创建匹配的 CC 付款请求。"),
        ("The user approves the payment through their Canton Wallet, which creates an accepted payment contract on the ledger.",
         "用户通过 Canton 钱包批准付款，在账本创建已接受付款合约。"),
        ("The provider processes the accepted payment and updates the license with a new expiration date.",
         "提供方处理已接受付款并更新许可过期日。"),
        ("This section helps you become familiar with a Canton Network (CN) business operation within the CN App Quickstart. The App Quickstart application is intended to be extended by your team to meet your business needs. When you are familiar with the App Quickstart, review the technology choices and application design to determine what changes are needed. Technology and design decisions are ultimately up to you.",
         "本节帮助你在 CN App Quickstart 中熟悉一次 CN 业务操作。应用可由团队扩展；熟悉后请审视技术选型与设计。技术与设计决策由你决定。"),
        ("If you find errors, please contact your representative at Digital Asset.", "发现错误请联系 Digital Asset 代表。"),
        ("Install the [CN App Quickstart](/appdev/quickstart/prerequisites) before beginning this demonstration.",
         "演示前请先完成 [CN App Quickstart 安装](/appdev/quickstart/prerequisites)。"),
        ("The CN App Quickstart can run with or without authorization, based on your business needs. Toggle authorization with the `make setup` command in the `quickstart` subdirectory. `make setup` asks to enable Observability, OAUTH2, and specify a party hint. In this demo, we disable `TEST MODE`, use the default party hint, and show OAUTH2 as enabled and disabled. When OAUTH2 makes a difference, we display both paths, one after the other. You can follow your path and ignore the other. You may enable Observability, but it is not required for this demo.",
         "CN App Quickstart 可按需启用授权；在 `quickstart` 子目录用 `make setup` 切换。演示关闭 `TEST MODE`、使用默认 party hint，并分别展示启用/未启用 OAUTH2 的路径，任选其一即可。Observability 可选。"),
        ("**Choose your adventure:**", "**选择你的路径：**"),
        ("`make setup` **without** OAUTH2:", "`make setup` **未启用** OAUTH2："),
        ("`make setup` **with** OAUTH2:", "`make setup` **启用** OAUTH2："),
        ("Build and start App Quickstart:", "构建并启动 App Quickstart："),
        ("Open an incognito browser and navigate to:", "用无痕浏览器打开："),
        ("Alternatively, in the terminal, from quickstart/ run:", "或在 quickstart/ 终端运行："),
        ("  Safari users may need to manually map the `app-provider` subdomain in `/etc/hosts`. Use the terminal command `sudo nano /etc/hosts` to add:",
         "  Safari 用户可能须在 `/etc/hosts` 手动映射 `app-provider` 子域：`sudo nano /etc/hosts` 添加："),
        ("  This tells your system to resolve `app-provider.localhost` to your local machine. Then save and close the file. Restart Safari.",
         "  使系统将 `app-provider.localhost` 解析到本机，保存后重启 Safari。"),
        ("**OAUTH2 disabled**", "**未启用 OAUTH2**"),
        ("When OAUTH2 is **disabled**, the homepage presents a simple login field. Begin by logging in as the `AppProvider` by entering \"app-provider\" in the User field.",
         "未启用 OAUTH2 时，首页为简单登录框；在 User 字段输入 \"app-provider\" 以 `AppProvider` 登录。"),
        ("**OAUTH2 enabled**", "**已启用 OAUTH2**"),
        ("When OAUTH2 is **enabled**, the homepage prompts to login with Keycloak's OAuth 2.0 portal:",
         "启用 OAUTH2 时，首页通过 Keycloak OAuth 2.0 门户登录："),
        ("Make a mental note that `AppProvider`’s username is “app-provider” and the password is \"abc123\" (all lowercase).",
         "请记住 `AppProvider` 用户名为 app-provider，密码为 abc123（全小写）。"),
        ("Login with `app-provider` with keycloak.", "在 Keycloak 以 app-provider 登录。"),
        ("Fill in the login credentials: username: app-provider, password: abc123", "凭据：用户名 app-provider，密码 abc123"),
        ("### The App Installs Menu", "### 应用安装菜单"),
        ("Once you are logged in select **AppInstalls** in the menu.", "登录后选择菜单 **AppInstalls**。"),
        ("Open a terminal to create an app install request.", "打开终端创建应用安装请求。"),
        ("From `/quickstart/` run:", "在 `/quickstart/` 运行："),
        ("This command creates an App Installation Request on behalf of the Participant.",
         "该命令代表 Participant 创建应用安装请求。"),
        ("  If your machine is not powerful enough to host `LocalNet` or if the docker containers are not responsive then the response may show a failure with status code 404 or 000 (as shown in the image below). Increasing Docker memory limit to at least 8 GB should allow the `LocalNet` containers to operate properly.",
         "  若机器不足以运行 `LocalNet` 或容器无响应，可能返回 404/000；将 Docker 内存增至至少 8 GB 通常可恢复。"),
        ("Return to the browser.", "回到浏览器。"),
        ("The install request appears in the list.", "安装请求出现在列表中。"),
        ("Click **Accept**.", "点击 **Accept**。"),
        ("The `AppInstallRequest` is Accepted.", "`AppInstallRequest` 已接受。"),
        ("The actions update to Cancel and Create license.", "操作更新为 Cancel 与 Create license。"),
        ("Click **Create License**. The license is created and the “# Licenses” field is updated.",
         "点击 **Create License**；许可已创建，“# Licenses” 字段更新。"),
        ("Next, navigate to the Licenses menu and select **Renewals**.", "进入 Licenses 菜单选择 **Renewals**。"),
        ("A \"License Renewal Request” modal opens with an option to renew a license.",
         "打开「License Renewal Request」模态框。"),
        ("Click **New** to open the \"Renew License\" modal.", "点击 **New** 打开 Renew License 模态框。"),
        ("In the modal, set the number of days to renew the license, the fee, time to prepare the license, and time to settle the license. You must add a description to proceed.",
         "在模态框设置续期天数、费用、准备时间与结算时间；须填写描述。"),
        ("\"Prepare in\" is an indication for the sender (app-user) that they are expected to accept allocation before that time. \"Settle in\" is a time that the provider has to `completeRenewal`. After that, the allocation will be expired.",
         "「Prepare in」提示 app-user 须在此前接受分配；「Settle in」为提供方完成 `completeRenewal` 的期限，逾期分配失效。"),
        ("Click **Issue License Renewal Request**.", "点击 **Issue License Renewal Request**。"),
        ("Per the Daml contract, licenses are created in an expired state. To activate the license, a renewal payment request must be issued.",
         "按 Daml 合约，许可创建时为过期；须发出续期付款请求以激活。"),
        ("To make payment, navigate to the Canton Wallet at [http://wallet.localhost:2000/allocations](http://wallet.localhost:2000/allocations) and log in as `app-user` if prompted.",
         "付款请打开 [Canton 钱包](http://wallet.localhost:2000/allocations)，按需以 `app-user` 登录。"),
        ("You can find the wallet's location by:", "查找钱包位置："),
        ("1. Reading the [LocalNet Application UIs reference](/sdks-tools/development-tools/localnet#application-uis).",
         "1. 阅读 [LocalNet 应用 UI 参考](/sdks-tools/development-tools/localnet#application-uis)。"),
        ("2. Navigating to the App Provider's \"Tenants\" menu.", "2. 进入应用提供方「Tenants」菜单。"),
        ("3. Logging into the app as `app-user`, navigating to the Licenses menu, then clicking the **Renewals** action.",
         "3. 以 `app-user` 登录应用，在 Licenses 菜单点击 **Renewals**。"),
        ("If prompted, log in to the CC Wallet as `app-user`.", "若提示，以 `app-user` 登录 CC 钱包。"),
        ("If your wallet does not have CC then enter an amount and click **TAP**. After a moment, the available balance will automatically update.",
         "若钱包无 CC，输入金额并点击 **TAP**；余额将自动更新。"),
        ("Once your CC wallet is loaded, navigate to the \"Allocations\" menu and accept the \"Allocation Request\" before the \"Allocate before\" time expires.",
         "钱包有余额后，在 Allocations 菜单于「Allocate before」前接受 Allocation Request。"),
        ("If the allocation request is accepted, a new \"Allocations\" section appears. This section shows the `licenseFeePayment` information.",
         "接受后会出现 Allocations 区，显示 `licenseFeePayment` 信息。"),
        ("Return to the Quickstart as the `AppProvider`. In the Licenses menu, select **Renewals**. This opens the License Renewals Request modal. Click the green **Complete Renewal** button.",
         "以 `AppProvider` 回到 Quickstart，在 Licenses 选择 **Renewals**，点击绿色 **Complete Renewal**。"),
        ("A confirmation appears that the license renewal completed successfully.",
         "出现许可续期成功确认。"),
        ("Log out from the `AppProvider` and log in as `AppUser`.", "退出 `AppProvider` 并以 `AppUser` 登录。"),
        ("If OAUTH2 is disabled, simply log in as `app-user`.", "未启用 OAUTH2 时直接以 app-user 登录。"),
        ("When OAUTH2 is enabled, you log in using the app-user username and password.",
         "启用 OAUTH2 时用 app-user 用户名与密码登录。"),
        ("Login as `AppUser` with “app-user” as the username and the password is “abc123”.",
         "以 AppUser 登录：用户名 app-user，密码 abc123。"),
        ("The AppInstall now shows as accepted.", "AppInstall 显示为已接受。"),
        ("The license shows as active.", "许可显示为 active。"),
        ("Congratulations. You’ve successfully created and activated a license with a payment allocation in Canton wallet!",
         "恭喜！你已在 Canton 钱包中完成许可创建、付款分配与激活！"),
        ("The Canton Console connects to the running application ledger. The console allows a developer to bypass the UI to interact with the CN in a more direct manner. For example, in Canton Console you can connect to the Participant to see the location of the Participant and their synchronizer domain.",
         "Canton Console 连接运行中的应用账本，可绕过 UI 直接交互，例如查看 Participant 位置与 synchronizer 域。"),
        ("Activate the Canton Console in a terminal from the `quickstart/` directory. Run:", "在 `quickstart/` 运行："),
        ("After the console initiates, run the `participants` and `participants.all` commands, respectively.",
         "启动后分别运行 `participants` 与 `participants.all`。"),
        ("Returns a detailed categorization of participants.", "返回 participant 详细分类。"),
        ("Shows a list of all participant references.", "列出所有 participant 引用。"),
        ("On `LocalNet`, you can connect to any of the listed participants. Connect to the app user's validator with",
         "在 `LocalNet` 可连接任一列出的 participant。连接 app user 验证者："),
        ("If you receive an error, double check that you used the backticks.", "若报错请确认使用了反引号。"),
        ("The app provider can be connected with:", "连接 app provider："),
        ("Connect to the Super Valdiator that is simulating the Global Synchronizer using:",
         "连接模拟 Global Synchronizer 的超级验证者："),
        ("Canton Console also provides a diagnostic tool that displays the health of Canton Network validators:",
         "Canton Console 还提供验证者健康诊断："),
        ("Daml Shell connects to the running PQS database of the application provider’s Participant. In the Shell, the assets and their details are available in real time.",
         "Daml Shell 连接应用提供方 Participant 的 PQS；可实时查看资产与详情。"),
        ("Run the shell from quickstart/ in the terminal with:", "在 quickstart/ 运行："),
        ("Run the following commands to see the data:", "运行下列命令查看数据："),
        ("Shows unique identifiers and the asset count:", "显示唯一标识与资产数量："),
        ("List the license details.", "列出许可详情。"),
        ("Displays license renewal request details.", "显示许可续期请求详情。"),
        ("Shows any archived license(s).", "显示已归档许可。"),
        ("Explore the CC Scan Web UI at [http://scan.localhost:4000/](http://scan.localhost:4000/).",
         "在 [http://scan.localhost:4000/](http://scan.localhost:4000/) 打开 CC Scan。"),
        ("The default activity view shows the total CC balance and the Validator rewards.",
         "默认活动视图显示 CC 总余额与验证者奖励。"),
        ("Select the **Network Info** menu to view SV identification.", "选择 **Network Info** 查看 SV 标识。"),
        ("The Validators menu shows that the local validator has been registered with the SV.",
         "Validators 菜单显示本地验证者已向 SV 注册。"),
        ("  Observability may no longer work while App Quickstart is under revisions.", "  App Quickstart 修订期间 Observability 可能不可用。"),
        ("In a web browser, navigate to [http://localhost:3030/dashboards](http://localhost:3030/dashboards) to view the observability dashboards. Select **Quickstart - consolidated logs**.",
         "浏览器打开 [http://localhost:3030/dashboards](http://localhost:3030/dashboards)，选择 **Quickstart - consolidated logs**。"),
        ("The default view shows a running stream of all services.", "默认视图显示所有服务日志流。"),
        ("Change the services filter from “All” to “participant” to view participant logs. Select any log entry to view its details.",
         "将服务过滤从 All 改为 participant；点击条目查看详情。"),
        ("Navigate to [http://sv.localhost:4000/](http://sv.localhost:4000/) for the SV Web UI. The SV view displays data directly from the validator in a GUI that is straightforward to navigate.",
         "SV Web UI：[http://sv.localhost:4000/](http://sv.localhost:4000/)，数据直接来自验证者。"),
        ("Login as ‘sv’.", "以 sv 登录。"),
        ("The UI shows information about the SV and lists the active SVs.", "UI 显示 SV 信息与活跃 SV 列表。"),
        ("The Validator Onboarding menu allows for the creation of validator onboarding secrets.",
         "Validator Onboarding 菜单可创建验证者 onboarding secret。"),
        ("You've completed a business operation in the CN App Quickstart and have been introduced to the basics of the Canton Console and Daml Shell. We encourage you to explore the CN App Quickstart codebase and modify it to meet your business needs. You might be interested in learning more about the [App Quickstart project structure](/appdev/quickstart/project-structure) or the application development modules in [Module 4: Building Applications](/appdev/modules/m4-building-apps-intro).",
         "你已完成 CN App Quickstart 中的一次业务操作，并初步了解 Canton Console 与 Daml Shell。建议探索代码库并按业务修改；可继续阅读[项目结构](/appdev/quickstart/project-structure)或[模块 4：构建应用](/appdev/modules/m4-building-apps-intro)。"),
    ]
    p.extend(COMMON)
    out = apply(en, "运行演示", "运行演示", h, p)
    (BODY / "appdev-quickstart-running-the-demo.zh.txt").write_text(out, encoding="utf-8")
    print("running-demo", len(out))


def observability():
    en = (BODY / "appdev-quickstart-observability-and-tracing.en.txt").read_text()
    h = {
        "# Canton Network Quickstart observability & troubleshooting overview": "# Canton Network Quickstart 可观测性与排障概览",
        "## Overview of observability": "## 可观测性概览",
        "### The LocalNet configuration": "### LocalNet 配置",
        "### Observability overview": "### 可观测性组件概览",
        "#### Daml Shell": "#### Daml Shell",
        "#### Grafana": "#### Grafana",
        "#### Direct Postgres access": "#### 直接访问 Postgres",
        "#### Interactive debugger": "#### 交互式调试器",
        "## Observability and tracing": "## 可观测性与追踪",
        "### Correlation identifiers": "### 关联标识符",
        "### Direct Ledger inspection using correlation identifiers": "### 用关联 ID 直接检查账本",
        "### Correlated Logs and Traces using Correlation Identifiers": "### 用关联 ID 关联日志与追踪",
    }
    p = [
        ("  The screenshots in this guide are taken from multiple sessions and are inconsistent with each other. This will be rectified once some of the updates are committed.",
         "  本指南截图来自多次会话，彼此不一致；待更新提交后将统一。"),
        ("It's assumed that you have read the quickstart getting started guide and explore the demo. If you haven't, we strongly encourage those documents to establish a baseline understanding of observability.",
         "假定你已阅读 quickstart 入门与演示文档；若未读，强烈建议先建立可观测性基础认知。"),
        ("The Canton Network quickstart deployment configuration includes a full observability suite. Tools preconfigured for monitoring and troubleshooting distributed Canton applications—both in development and production. The observability suite provides three key types of monitoring data:",
         "CN quickstart 部署含完整可观测性套件，预配置用于开发/生产环境监控与排障，提供三类监控数据："),
        ("* **consolidated structured logs** for application and system events", "* **合并结构化日志**（应用与系统事件）"),
        ("* **distributed traces** that visualize end-to-end transaction flows; and", "* **分布式追踪**（端到端交易流）；以及"),
        ("* **metrics** for monitoring key performance indicators.", "* **指标**（关键性能指标）。"),
        ("The suite allows data types to be correlated with each other to provide insights for root cause analysis. In addition, the Canton Ledger also provides a variety of correlation and tracing ids that permit tracking transaction provenance across multiple organizations and environments.",
         "套件支持数据互相关联以做根因分析；Canton 账本亦提供多种关联/追踪 ID，跨组织与环境追踪交易来源。"),
        ("The Quickstart runtime configuration is defined in `.env.local`, which allows the option to bring up a local deployment of the Observability Stack. This file can be created using `$ make setup`, which wraps the command `$ ./gradlew configureProfiles --no-daemon --console=plain --quiet`, or can be edited manually to set environment variables `LOCALNET_ENABLED` and `OBSERVABILITY_ENABLED` to `true` or `false` as desired.",
         "Quickstart 运行时配置在 `.env.local`，可启用本地 Observability Stack；可用 `$ make setup`（包装 configureProfiles）创建，或手动设置 `LOCALNET_ENABLED`、`OBSERVABILITY_ENABLED`。"),
        ("The `LocalNet` runtime configuration is handled by `docker-compose` configured in `compose.yaml` using environment variables from `.env` in the `quickstart/` project root directory. The usual Docker commands and tooling applies.",
         "`LocalNet` 由 `quickstart/` 根目录 `.env` 驱动的 `compose.yaml` 中 docker-compose 管理；适用常规 Docker 命令。"),
        ("Immediately useful commands you probably already know:", "可能已熟悉的常用命令："),
        ("* `$ docker ps` lists the running containers.", "* `$ docker ps` 列出运行中容器。"),
        ("* `$ docker logs [-f] <container>` fetches the logs of a container, and follow the logs with the `-f` option.",
         "* `$ docker logs [-f] <container>` 获取/跟踪容器日志。"),
        ("  * If the system is not working well to the extent you do not trust the observability stack (discussed later), `docker logs backend-service` is a good place to start looking for errors that might provide an insight into what has gone wrong.",
         "  * 若系统异常且不信任可观测性栈，`docker logs backend-service` 是查错的起点。"),
        ("* `$ docker restart <container>` for those instances where a container seems to have become stuck.",
         "* `$ docker restart <container>` 用于容器卡住时。"),
        ("The Quickstart application provides a foundational production Daml application. It includes a full observability configuration which is helpful to troubleshoot or debug an application. As a working demo, Quickstart is opinionated regarding its technology stack. However, the platform itself is agnostic. Individual components can be replaced as required.",
         "Quickstart 提供生产级 Daml 应用基础与完整可观测性配置；技术栈有既定选择，但平台本身中立，组件可按需替换。"),
        ("The current troubleshooting and debugging services include:", "当前排障与调试服务包括："),
        ("* Local ledger inspection via [Daml Shell](/sdks-tools/cli-tools/daml-shell)",
         "* 经 [Daml Shell](/sdks-tools/cli-tools/daml-shell) 本地检查账本"),
        ("* Datasource collection and management via **OpenTelemetry**", "* 经 **OpenTelemetry** 采集与管理数据源"),
        ("  * This uses the **OTEL Collector** ([https://opentelemetry.io/docs/collector](https://opentelemetry.io/docs/collector))",
         "  * 使用 **OTEL Collector**（[文档](https://opentelemetry.io/docs/collector)）"),
        ("* Metrics are aggregated using **Prometheus** ([https://prometheus.io/](https://prometheus.io/))",
         "* 指标由 **Prometheus** 聚合（[https://prometheus.io/](https://prometheus.io/)）"),
        ("* Logs are inspected with **lnav** (see the [lnav download and documentation](/appdev/quickstart/lnav) page)",
         "* 日志用 **lnav** 检查（见 [lnav 文档](/appdev/quickstart/lnav)）"),
        ("* Traces are aggregated using **Tempo** ([https://grafana.com/oss/tempo/](https://grafana.com/oss/tempo/))",
         "* 追踪由 **Tempo** 聚合（[https://grafana.com/oss/tempo/](https://grafana.com/oss/tempo/)）"),
        ("* Aggregated observations (metrics, logs, and traces) are viewable via **Grafana** ([https://grafana.com/oss/grafana/](https://grafana.com/oss/grafana/)) which acts to allow hyperlinked exploration of the Observability fields.",
         "* **Grafana** 可查看聚合观测并超链接跳转（[https://grafana.com/oss/grafana/](https://grafana.com/oss/grafana/)）。"),
        ("Daml Shell is a terminal application that provides interactive local ledger inspection on top of PQS. Quickstart is configured to launch Daml Shell in a Docker container and is configured to connect to the included application provider’s PQS instance. This is easiest to access via the top-level project scripts accessed via `make` from `quickstart/`. To see this in action, build and start the quickstart app then:",
         "Daml Shell 在 PQS 之上交互检查本地账本；Quickstart 在 Docker 中启动并连接应用提供方 PQS。构建启动后："),
        ("Run `$ make create-app-install-request` to use `curl` to submit the `create AppInstallRequest ...` command to the ledger[^1] to initiate user onboarding[^2]. Then you can use the following Daml Shell commands:",
         "运行 `$ make create-app-install-request` 向账本提交 `create AppInstallRequest`[^1] 以启动用户入驻[^2]，然后："),
        ("\\> `active` to see a summary of the contracts you created; and,", "\\> `active` 查看已创建合约摘要；"),
        ("\\> `active quickstart-licensing:Licensing.AppInstall:AppInstallRequest` to see the contract details for any Asset contracts on the ledger; finally,",
         "\\> `active quickstart-licensing:Licensing.AppInstall:AppInstallRequest` 查看合约详情；"),
        ("\\> `contract [contract-id from the previous command]`[^3] to see the full detail of the `AppInstallRequest` contract on the ledger.",
         "\\> `contract [合约 ID]`[^3] 查看 `AppInstallRequest` 完整详情。"),
        ("\\> `help [command]` provides context help for daml shell commands.[^4]",
         "\\> `help [command]` 提供命令帮助[^4]。"),
        ("Grafana is accessible via its web interface, which is port-mapped to [http://localhost:3030/](http://localhost:3030/), and can be opened in the current browser from the command line using `make open-observe`.",
         "Grafana Web UI 映射到 [http://localhost:3030/](http://localhost:3030/)，可用 `make open-observe` 打开。"),
        ("Your debugging should focus on using Grafana's trace and log facilities, as well as ledger inspection via Daml Shell. If you make sure that your exported logs and traces are sufficient to support debugging during development, they are more likely to support diagnostics in production, as well.",
         "调试应优先用 Grafana 追踪/日志与 Daml Shell 账本检查；开发期日志/追踪充足则生产排障更可靠。"),
        ("There is additional access configured into the Quickstart that can assist with debugging on `LocalNet`. Use the same diagnostic tools for development as you will for production. If you add a log line that allows you to identify and fix a bug in development, then keeping it around at `trace` or `debug` log levels increases your operational readiness. Using tools that won’t be available in production to debug in development reduces operational readiness.",
         "Quickstart 在 `LocalNet` 上配置了额外调试访问；开发与生产应使用相同诊断工具；保留 trace/debug 日志有助于运维就绪。"),
        ("All persistent state in the example application is stored in one or more postgres databases. You can use the postgres configuration in `.env` to connect directly to these instances.",
         "示例应用持久状态存于 Postgres；可用 `.env` 配置直连。"),
        ("For example: if you connect to the `postgres-splice-app-provider` container (default username `cnadmin`, dbname `scribe`, and password `supersafe`; then you can use the SQL interface to PQS to examine the app-provider’s participant’s local ledger. The SQL API to PQS is documented in the daml [documentation]().",
         "例如连接 `postgres-splice-app-provider`（默认用户 cnadmin、库 scribe、密码 supersafe）可用 SQL 检查应用提供方 participant 本地账本。"),
        ("If you review the `compose.yaml` file and examine the configuration for backend-service you will see the lines:",
         "查看 `compose.yaml` 中 backend-service 配置可见："),
        ("This enables remote debugging of the Java component backend in the user application (backend-service). You can use this to connect an IDE Debugger to the service at runtime if required. We recommend Grafana as your first resort, along with inspecting consolidated logs with [lnav](/appdev/quickstart/lnav). This keeps the system debuggable in production.",
         "这可远程调试 Java 后端；必要时 IDE 附加调试。仍建议优先 Grafana 与 [lnav](/appdev/quickstart/lnav)，以保持生产可调试性。"),
        ("Faulty distributed systems can be notoriously hard to diagnose. From the start of a project, Quickstart provides the sort of observability and diagnostics facilities that are otherwise often only developed toward the end. Simplifying diagnostics for new Canton Network Applications from the outset of each project is one of the motivations behind the development of Quickstart.",
         "分布式系统故障难诊断；Quickstart 从项目伊始即提供通常到后期才完善的可观测性与诊断能力。"),
        ("The links in the overview include the official user and reference documentation for the various tools included in Quickstart. While there is no substitute for the official documentation, it is hoped the following tour of the capabilities configured into Quickstart can provide a starting point for your own experimentation.",
         "概览中的链接为各工具官方文档；下文 Quickstart 能力导览可作为实验起点。"),
        ("Inspecting Canton begins by correlating identifiers, much like inspecting any other distributed system. Canton can accept and/or generate a number of identifiers suitable for correlating across both time, various nodes, and the evolving state of the ledger.",
         "检查 Canton 从关联标识符开始；Canton 可接受/生成多种 ID，用于跨时间、节点与账本状态关联。"),
        ("A few of the key identifiers to be aware of are:", "关键标识符包括："),
        ("| `Identifier`       | `Specified by`                | `Scope`",
         "| 标识符 | 指定方 | 范围 |"),
        ("| `ApplicationId`    | `The Ledger Client`           | `Identifies the ledger client during command submission and processing.`",
         "| `ApplicationId` | Ledger 客户端 | 命令提交与处理时标识客户端 |"),
        ("| `WorkflowId`       | `The Ledger Client`           | `Identifies the business process. Persisted to the ledger.`",
         "| `WorkflowId` | Ledger 客户端 | 标识业务流程，持久化到账本 |"),
        ("| `CommandId`        | `The Ledger Client`           | `Identifies the business “act” associated with a ledger command. Persisted to the ledger. Visible only to the submitting party. Common across retries.`",
         "| `CommandId` | Ledger 客户端 | 标识业务“动作”，仅提交方可见，重试共用 |"),
        ("| `SubmissionId`     | `The Ledger Client`           | `Identifies an individual ledger submission to a participant node.`",
         "| `SubmissionId` | Ledger 客户端 | 标识单次提交 |"),
        ("| `TransactionId`    | `Daml Ledger`                 | `Global identifier for a committed transaction to the ledger. Only visible to participant nodes that witness or are informed of the transaction.`[^5]",
         "| `TransactionId` | Daml 账本 | 已提交交易的全局 ID[^5] |"),
        ("| `LedgerEventId`    | `Daml Ledger`                 | `Global identifier for a node within a committed transaction tree corresponding to a ledger event.`",
         "| `LedgerEventId` | Daml 账本 | 账本事件在交易树中的全局 ID |"),
        ("| `Trace/SpanId`[^6] | `Ledger Client (or upstream)` | `Accepted by GRPC/HTTP ledger interfaces and honoured throughout the Canton Network code. Where one is not provided may sometimes be generated internally to provide tracing support within the network.`",
         "| `Trace/SpanId`[^6] | 客户端或上游 | gRPC/HTTP 接口接受并在全网传递[^6] |"),
        ("| `LedgerOffset`     | `Participant Node`            | `The height of a transaction within the local linearization of the ledger by a participant node.`[^7]",
         "| `LedgerOffset` | Participant | 本地账本线性化中的高度[^7] |"),
        ("| `ContractId`       | `Daml Ledger`                 | `Global identifier for a contract that was created successfully on the ledger at some point. If the contract has been subsequently archived the id remains a stable and valid way to refer to it even though the associated contract can no longer be used.`",
         "| `ContractId` | Daml 账本 | 曾成功创建的合约全局 ID |"),
        ("| `TemplateId`       | `Daml Application`            | `Combined with a PackageId this provides a global identifier for a Daml smart contract.`",
         "| `TemplateId` | Daml 应用 | 与 PackageId 组合为全局模板 ID |"),
        ("| `PartyId`          | `Participant Node`            | `Identifier of the Party on the Canton ledger.`[^8]",
         "| `PartyId` | Participant | Canton 账本上的 Party 标识[^8] |"),
        ("Useful Correlation Identifiers", "常用关联标识符"),
        ("The goal of the observability configuration is to make it easier to navigate through the provenance of any state or event in the wider system. Any or all of these identifiers can be used to correlate a combination of logs, metrics, and state. Three of these in particular are intended to be set to corresponding business identifiers derived from your specific business domain: application-id, workflow-id, and command-id.",
         "可观测性配置旨在便于在系统中导航任意状态/事件的来源；这些 ID 可关联日志、指标与状态；application-id、workflow-id、command-id 宜映射业务域标识。"),
        ("Navigation is enabled by the use of structured logs from as many components as possible[^9]. It is recommended that your custom components likewise emit structured logs for more accurate consumption by OpenTelemetery.",
         "导航依赖各组件结构化日志[^9]；建议自定义组件亦输出结构化日志供 OpenTelemetry 消费。"),
        ("Starting from `$ make stop clean-all && make build start`, we proceed with initiating the example application app-user onboarding:",
         "从 `$ make stop clean-all && make build start` 开始，发起 app-user 入驻示例："),
        ("This is the output of a script submitting a create command to the app-user’s participant node, it already contains number of the correlation ids mentioned above:",
         "脚本向 app-user participant 提交 create 命令的输出已含多种关联 ID："),
        ("We can immediately use the transaction id in Daml Shell to view the associated ledger transaction:",
         "可立即在 Daml Shell 用 transaction id 查看账本交易："),
        ("From here we can get more identifiers:", "由此可获得更多标识符："),
        ("The Workflow Id, Template Id, and Party Ids are also visible here. The ledger offset can be very useful if you are going to query PQS or the Ledger API directly for more information. The Contract Id can be used to immediately display the contract in Daml Shell:",
         "Workflow Id、Template Id、Party Id 亦可见；Ledger offset 便于查 PQS/Ledger API；Contract Id 可在 Daml Shell 显示合约。"),
        ("If the problem is a bug in your smart contract, then exploring the transaction and related provenance within Daml Shell and using the Daml IDE to synthesize and rerun the relevant transactions will normally identify the issue. However, if only due to the comparative lines of code, the root cause of most issues will be off ledger. Consequently, significant value in these identifiers derives from correlating these identifiers with the consolidated logs and other information collected through Open Telemetry.",
         "智能合约缺陷可在 Daml Shell/IDE 中重放交易定位；多数问题根因在链下，故将这些 ID 与 OpenTelemetry 合并日志关联很有价值。"),
        ("To advance the example, we log in as the AppProvider and accept the AppInstallRequest, resulting in:",
         "继续示例：以 AppProvider 登录并接受 AppInstallRequest："),
        ("The usual browser-based developer inspection tools can extract the relevant correlation ids:",
         "浏览器开发者工具可提取关联 ID："),
        ("We can also see the HTTP call to the Backend-Service when we issue a new license, and again the response to the call provides additional identifiers.",
         "签发新许可时可见对 Backend-Service 的 HTTP 调用，响应亦含更多 ID。"),
        ("As we have already seen, contract ids can be used in Daml Shell to inspect the contracts directly. In addition, due to the way the OpenAPI interface for the Backend has been designed, the Command Id is visible as a query parameter to the POST. We can use this to query the consolidated logs in Grafana:",
         "合约 ID 可在 Daml Shell 检查；Backend OpenAPI 将 Command Id 作为 POST 查询参数，可用于 Grafana 查询合并日志："),
        ("The command-id has provided logs from the App-Provider’s Nginx reverse proxy in front of the backend and their Participant Node. We can verify the Nginx log matches the request we saw from the browser:",
         "command-id 关联到应用提供方 Nginx 与 Participant 日志；可核对 Nginx 与浏览器请求一致。"),
        ("Critically, we can also see in the same aggregated log the entries that indicate the Participant Node submitting the transaction to the Canton Synchronization Domain:",
         "同一聚合日志中可见 Participant 向 Canton 同步域提交交易。"),
        ("Was notified that the transaction was successfully committed to the Canton Ledger:",
         "并通知交易已成功提交到 Canton 账本："),
        ("And finally added to the App-Provider’s local ledger:[^10]",
         "最终写入应用提供方本地账本[^10]："),
        ("Note that from these we can obtain additional correlation ids, any of which could have been used to find these log lines:",
         "由此还可获得其他关联 ID，任一条均可定位这些日志："),
        ("| Ledger Offset   |   | 000000000000000088", "| Ledger Offset | | 000000000000000088 |"),
        ("| T ransaction Id |   | 122053c509d405e77eab680a855…2d10bb", "| Transaction Id | | … |"),
        ("In particular the Trace Id is invaluable because it can link us directly into Tempo to see the distributed operation spans:",
         "Trace Id 尤其重要，可直达 Tempo 查看分布式 span："),
        ("Here we can see the flow of the create license operation behind the backend reverse proxy:",
         "可见后端反向代理后 create license 操作流："),
        ("* Initial POST handler in the Backend Service", "* Backend Service 初始 POST 处理"),
        ("* Backend query against PQS to retrieve the AppInstall contract", "* 后端查询 PQS 获取 AppInstall"),
        ("* Call to the App-Provider Ledger API from the Backend Service", "* 后端调用应用提供方 Ledger API"),
        ("* Preparation of the Transaction by the Participant Node and submission to the Canton Network",
         "* Participant 准备交易并提交 Canton Network"),
        ("One very powerful aspect of the Grafana suite is the degree to which it integrates the various observability tools in the quickstart stack. We have already seen this with the link from the consolidated logs to Tempo; however, it also runs the other way. Expanding a span in Tempo provides a link to “Logs for this span”.",
         "Grafana 套件强大之处在于整合日志、追踪：合并日志可链到 Tempo，展开 span 可查看「Logs for this span」。"),
        ("These link to the logs for the specific component (backend-service, participant, sequencer, etc) correlated to this span.",
         "链接到与该 span 关联的各组件日志。"),
        ("Using different correlation ids can allow us to navigate and explore the history of our distributed application. We have seen the transaction committed to the ACS within the participant node; however, PQS also logs identifiers associated with the transactions it indexes.",
         "不同关联 ID 可导航分布式应用历史；PQS 索引交易时亦记录相关 ID。"),
        ("The transactionId and the traceId can both be used to broaden our understanding of the create-license backend operation and what followed after.",
         "transactionId 与 traceId 可扩展对 create-license 及后续操作的理解。"),
        ("PQS ingestion is a distinct operation performed by a background process. The traceId for this log is therefore distinct; however it still links back to the trace and transaction identifiers associated with the ledger data it is ingesting. You can see this if you follow the Tempo link:",
         "PQS 摄取为后台独立操作，traceId 不同但仍链回账本数据的 trace/transaction。"),
        ("The expanded “references” section in the “export transaction” span include links to traces for related PQS processes and also, critically, the trace for command submission that resulted in the transaction. The link takes us directly to that trace, which in this case is the same one we just came from.",
         "export transaction span 的 references 含相关 PQS 追踪及导致该交易的命令提交追踪。"),
        ("Querying and navigating through correlated logs, traces, and spans makes understanding the multiple moving parts involved in a Canton Network Application much easier. Keep in mind that you can only navigate logs and traces that have been emitted; and, query identifiers that have been included or attached. Therefore we highly recommend you periodically take the time to look for opportunities to enrich and expand the logging within your application.",
         "关联查询日志/追踪/span 更易理解 CN 应用多组件；仅能导航已发出且附带 ID 的观测，建议持续丰富应用日志。"),
        ("One final thing that isn’t visible immediately, but is whenever you hover over any log line is the option to view the log context for that line:",
         "悬停日志行可查看该行上下文："),
        ("This will pop up a window with a full unfiltered view of the component’s logs for that time, with the relevant line highlighted. In the case of the Nginix log line, this provides a single click view of the other traffic being served at the same time:",
         "弹出该时刻组件未过滤日志并高亮相关行；例如可一次查看 Nginx 同时段其他流量。"),
        ("It is also worth keeping in mind that Grafana exposes access to the raw queries for Tempo and Prometheus. It is well worth the time to experiment with these and discover how to probe the unified metrics and traces available via the observability stack. For log inspection, use [lnav](/appdev/quickstart/lnav):",
         "Grafana 亦暴露 Tempo/Prometheus 原始查询，值得实验；日志检查用 [lnav](/appdev/quickstart/lnav)："),
        ("A starting point for finding documentation on these see:", "相关文档起点："),
        ("* lnav: [lnav download and documentation](/appdev/quickstart/lnav)", "* lnav：[文档](/appdev/quickstart/lnav)"),
        ("* Tempo: [https://grafana.com/docs/tempo/latest/traceql/](https://grafana.com/docs/tempo/latest/traceql/)", "* Tempo：[TraceQL](https://grafana.com/docs/tempo/latest/traceql/)"),
        ("* Prometheus: [https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/](https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/)",
         "* Prometheus：[查询编辑器](https://grafana.com/docs/grafana/latest/datasources/prometheus/query-editor/)"),
    ]
    p.extend(COMMON)
    en = re.sub(r"^# Observability and Tracing\n\n# Observability and Tracing\n\n", "# 可观测性与链路追踪\n\n", en)
    out = apply(en, "可观测性与链路追踪", "可观测性与链路追踪", h, p)
    (BODY / "appdev-quickstart-observability-and-tracing.zh.txt").write_text(out, encoding="utf-8")
    print("observability", len(out))


def json_api():
    en = (BODY / "appdev-quickstart-json-api.en.txt").read_text()
    en = re.sub(r"^# Using the JSON Ledger API\n\n# Using the JSON Ledger API\n\n# Using the JSON Ledger API\n\n",
                "# 使用 JSON Ledger API\n\n", en)
    h = {
        "## Overview": "## 概览",
        "## Prerequisites": "## 前置条件",
        "## LocalNet interaction expectations vs Explore the demo (using app vs developer skills)": "## LocalNet：演示 UI vs 开发者 API",
        "## Project directory structure": "## 项目目录结构",
        "## LocalNet env & auth": "## LocalNet 环境与认证",
        "### Env verification": "### 环境验证",
        "### Port mappings": "### 端口映射",
        "#### Security consideration": "#### 安全说明",
        "#### JSON API ports": "#### JSON API 端口",
        "#### Validator API ports": "#### Validator API 端口",
        "### OAuth2 & token mgmt": "### OAuth2 与令牌管理",
        "#### Overview": "#### 概览",
        "## JSON API Tutorial": "## JSON API 教程",
        "### Begin capture logs": "### 开始采集日志",
        "#### Lnav Guidance": "#### lnav 指引",
        "### Get a Token": "### 获取令牌",
        "### Use the token": "### 使用令牌",
        "### View Party and DSO activity in lnav": "### 在 lnav 中查看 Party 与 DSO",
        "### Save the DSO Party": "### 保存 DSO Party",
        "### Token management troubleshooting": "### 令牌管理排障",
        "## Create a party": "## 创建 party",
        "### See the new participant Alice in lnav": "### 在 lnav 中查看 Alice",
        "### Troubleshoot common party creation issues": "### 创建 party 常见问题",
        "## Upload a DAR": "## 上传 DAR",
        "### DAR Upload issues": "### DAR 上传问题",
        "## Create a contract on LocalNet": "## 在 LocalNet 创建合约",
        "### See the DAR activity in `lnav` by filtering the package ID": "### 在 lnav 按包 ID 过滤 DAR 活动",
        "### Create the Contract": "### 创建合约",
        "### Get PROVIDER\\_ADMIN\\_TOKEN": "### 获取 PROVIDER_ADMIN_TOKEN",
        "### Find the AppInstallRequest contract": "### 查找 AppInstallRequest 合约",
        "### Return to `daml shell` to query for the `AppInstall` contract ID": "### 在 daml shell 查询 AppInstall 合约 ID",
        "### Back to the shell terminal": "### 回到 shell 终端",
        "### Check that the token is valid": "### 检查令牌有效",
        "### Exercise the CreateLicense choice": "### 行使 CreateLicense",
        "### See the AppInstall request in lnav": "### 在 lnav 查看 AppInstall",
        "### Get the License contract ID in daml shell": "### 在 daml shell 获取 License 合约 ID",
        "### Save the license contract ID in a variable": "### 保存许可合约 ID",
        "### Generate a unique renewal request": "### 生成唯一续期请求",
        "### Set the license extension": "### 设置许可延期",
        "### Create the license renewal request": "### 创建许可续期请求",
        "### LicenseRenewalRequest": "### LicenseRenewalRequest",
        "### Return to the `daml shell`": "### 回到 daml shell",
        "### Regenerate the provider token in case of security-sensitive errors": "### 遇安全敏感错误时刷新提供方令牌",
        "### Return to the terminal and get a user token": "### 回到终端获取用户令牌",
        "### Look up the Allocation Contract ID": "### 查找 Allocation 合约 ID",
        "### Renew the token": "### 刷新令牌",
        "### Generate a unique command ID": "### 生成唯一 command ID",
        "### Set the endpoint path to connect to the backend service to complete the license renewal": "### 设置 complete-renewal 后端端点",
        "### Create a variable for the request body": "### 创建请求体变量",
        "### Make the request to complete the license renewal": "### 请求完成许可续期",
        "## Appendix": "## 附录",
        "### User token and IDs cookbook": "### 用户令牌与 ID 手册",
        "### Additional ports the default setup exposes": "### 默认暴露的额外端口",
        "### Health checks": "### 健康检查",
        "### Access admin ports": "### 访问 admin 端口",
        "### Show the Daml ledger API claims in your token": "### 查看令牌中的 Ledger API claims",
        "### How to discover the user and provider IDs": "### 如何发现用户与提供方 ID",
    }
    p = [
        ("You are ready to extend the CN Quickstart to interact directly with your LocalNet. You'll learn how to programmatically create parties, upload DARs, create contracts, and integrate with Canton Coin (Amulet) using OAuth2 authentication against your running LocalNet. By the end, you'll have the hands-on experience with critical API patterns needed to build your own Canton Network applications.",
         "你将扩展 CN Quickstart 以直接操作 LocalNet：以 OAuth2 编程创建 party、上传 DAR、创建合约并集成 Canton Coin（Amulet），掌握构建 CN 应用的关键 API 模式。"),
        ("This guide requires the Digital Asset Package Manager. Follow installation instructions at [DPM](/sdks-tools/cli-tools/dpm).",
         "本指南需要 Digital Asset Package Manager，安装见 [DPM](/sdks-tools/cli-tools/dpm)。"),
        ("You should have also finished the Quickstart installation and Explore the demo tutorial. We also recommend reading the developer journey lifecycle to better understand how Quickstart bootstraps your Canton Network development by providing the tooling you will need for any CN app.",
         "请完成 Quickstart 安装与演示教程；建议阅读开发者旅程以理解 Quickstart 如何为 CN 应用提供工具链。"),
        ("In the demo, you interacted with LocalNet through the web interface as a user. Now you'll take control of LocalNet directly through APIs, learning to programmatically manage the network infrastructure that will become your foundation for building on ScratchNet, TestNet, and beyond.",
         "演示中你通过 Web UI 使用 LocalNet；现在将通过 API 直接控制，为 ScratchNet、TestNet 等打下基础。"),
        ("The CN Quickstart contains the following directory structure:", "CN Quickstart 目录结构："),
        ("You'll work primarily in daml/ to extend the licensing contracts with a new LicenseHistory.daml contract that tracks ownership transfers",
         "主要在 daml/ 扩展许可合约（示例提及 LicenseHistory.daml 跟踪所有权转移）。"),
        ("The Quickstart application should be built and running. Verify that all services are operational in the terminal with `make status`.",
         "Quickstart 应已构建并运行；用 `make status` 确认服务正常。"),
        ("The port mappings for `LocalNet` expose the `AdminAPI` port and the `Postgres` port, both of which would normally be a security risk. However, having direct access to these ports when running on a local developer's machine can be useful. These ports should not be exposed when preparing deployment configurations for non-local deployments. The port suffixes are defined as environment variables. For any port mappings you wish to disable, you can find and remove the relevant Docker `port`: entry in the appropriate file.",
         "`LocalNet` 映射暴露 AdminAPI 与 Postgres 端口，公网有风险，本地开发有用；非本地部署勿暴露，可在 Docker 文件中移除 `ports`。"),
        ("(2975, 3975, 4975): Daml ops and smart contract deployment", "（2975、3975、4975）：Daml 运维与合约部署"),
        ("(2903, 3903, 4903): status monitoring", "（2903、3903、4903）：状态监控"),
        ("LocalNet uses Keycloak at [http://keycloak.localhost:8082](http://keycloak.localhost:8082) for OAuth2 authentication with two realms: `AppUser` and `AppProvider`. You can login to Keycloak at this port by using the username and password `admin`. Read `ref:keycloak-in-cnqs` To learn more about Keycloak.",
         "LocalNet 在 [http://keycloak.localhost:8082](http://keycloak.localhost:8082) 用 Keycloak OAuth2，realm 为 `AppUser` 与 `AppProvider`；可用 admin/admin 登录。详见 `ref:keycloak-in-cnqs`。"),
        ("In this tutorial, you're making API calls to simulate the steps taken in the Quickstart web app by requesting JWT tokens, then include them as Bearer tokens in API calls. Start the application and tools from the `quickstart/` directory.",
         "本教程用 API 模拟 Web 应用步骤：获取 JWT 作为 Bearer 调用 API；在 `quickstart/` 启动应用与工具。"),
        ("Allow capture logs to run in its terminal window. In a new terminal window, run the Quickstart application with `make start`. Once complete, this can become your working terminal window. After `make start` completes, open a new terminal window to initiate lnav. Start lnav with `lnav logs/*.clog` to capture and analyze logs. If there are no clogs you might try running `make stop && make clean-all` then rerunning `make start`. Alternatively, you can begin this guide to make transactions on the ledger. This should cause clogs to self-generate. This command launches lnav to trace transactions, debug issues, and monitor system behavior as you work. Keep lnav running in its terminal window.",
         "让 capture-logs 在单独终端运行；新终端 `make start` 后可作为工作终端；再开终端 `lnav logs/*.clog` 分析日志。若无 clog 可 `make stop && make clean-all` 后重启，或直接做账本交易以生成 clog。保持 lnav 运行。"),
        ("For detailed guidance on navigating lnav, and understanding the custom format, see `Debugging and troubleshooting with lnav`.",
         "lnav 导航与自定义格式详见 `Debugging and troubleshooting with lnav`。"),
        ("Use the AppUser validator client to get a token.", "用 AppUser 验证者客户端获取令牌。"),
        ("(client\\_secret is set in oauth2.env and AppUser-realm.json)", "（client_secret 在 oauth2.env 与 AppUser-realm.json）"),
        ("An empty return indicates success.", "空返回表示成功。"),
        ("Verify the token", "验证令牌"),
        ("List existing parties and include the token in API requests", "列出已有 party，请求携带令牌"),
        ("View Party activity in lnav with the `filter-in` command followed by the app provider or app user IDs.",
         "在 lnav 用 `:filter-in` 加 app provider 或 app user ID 查看 Party 活动。"),
        ("You can also view DSO activity in lnav using the DSO ID.", "亦可用 DSO ID 在 lnav 查看 DSO 活动。"),
        ("Save the `party` values for `app-provider` as APP\\_PROVIDER\\_PARTY and `app-user` as APP\\_USER\\_PARTY.",
         "将 app-provider、app-user 的 party 保存为 APP_PROVIDER_PARTY、APP_USER_PARTY。"),
        ("You're now ready to make authenticated JSON API calls to your LocalNet.", "现在可向 LocalNet 发起认证 JSON API 调用。"),
        ("Tokens expire after a period. If API calls return `Cannot iterate over null` or `401 Unauthorized`, regenerate your token with the command above. For production patterns, see `quickstart/docker/modules/splice-onboarding/docker/utils.sh` for token management utilities.",
         "令牌会过期；若返回 `Cannot iterate over null` 或 401，请重新获取；生产模式见 splice-onboarding 工具脚本。"),
        ("Create a new party on the AppUser validator.", "在 AppUser 验证者创建新 party。"),
        ("You can use any name as the `partyIdHint` value. Canton may append additional characters for uniqueness.",
         "`partyIdHint` 可任意命名；Canton 可能追加字符保证唯一。"),
        ("Success Response:", "成功响应："),
        ("Upload the prebuilt licensing DAR to the validator.", "向验证者上传预构建许可 DAR。"),
        ("Success looks like:", "成功形如："),
        ("404 Not Found: Verify DAR path is correct from your current directory 413 Payload Too Large: DAR exceeds size limit 409 Conflict: Package already uploaded curl: (52) Empty reply from server: Network issue - retry Check lnav for detailed upload logs and any processing errors.",
         "404：检查 DAR 路径；413：DAR 过大；409：包已上传；curl (52)：网络问题可重试；详见 lnav 上传日志。"),
        ("Inspect the DAR to find the package hash. Find and save the package ID, a 64-character hex string.",
         "检查 DAR 获取包哈希；保存 64 位十六进制 package ID。"),
        ("We suggest copying and pasting this command for your convenience. If you choose to type it out, you may need to type the full directory without the use of autocomplete.",
         "建议复制粘贴该命令；若手输可能需完整路径。"),
        ("The desired value may vary between SDK versions. You can identify the main package by the project name in the package list.",
         "所需值可能因 SDK 版本而异；在包列表中以项目名识别主包。"),
        ("Alternatively, if you're querying the `quickstart-licensing` DAR, as we do in this tutorial, you can quickly grep and save the project ID with:",
         "本教程查询 `quickstart-licensing` DAR 时可用 grep 快速保存 project ID："),
        ("If you'd like to query a different DAR then change the file path.", "查询其他 DAR 请改文件路径。"),
        ("Renew your token to query the participant:", "刷新令牌以查询 participant："),
        ("Get the user token:", "获取用户令牌："),
        ("Create the `AppInstallRequest`:", "创建 `AppInstallRequest`："),
        ("The return shows your first contract made on LocalNet via the JSON API ledger!", "返回表示你已通过 JSON API 在 LocalNet 创建首个合约！"),
        ("The return looks something like:", "返回类似："),
        ("updateId: A unique identifier for this ledger update/transaction. You can use this to track this specific operation in logs. completionOffset: The position in the ledger where this transaction was committed. For example, 1666 means this was the 1,666th transaction on this participant.",
         "updateId：账本更新/交易唯一 ID，可用于日志追踪。completionOffset：交易在账本中的位置，例如 1666 表示该 participant 第 1666 笔交易。"),
        ("See the contract creation in lnav by filtering for `AppInstallRequest` or filter by the `updateId` value.",
         "在 lnav 过滤 `AppInstallRequest` 或 updateId 查看创建。"),
        ("The results show detailed information including the trace IDs. Trace IDs can be used to follow related activity throughout the complete business operation.",
         "结果含 trace ID，可跟踪完整业务操作。"),
        ("In this screenshot, `deb9fe66dfb7990e5268f3690dbe53e8` and `61af0b8172d45909f9f8e8c5c4d46f16` are examples of trace IDs.",
         "截图中 `deb9fe66...` 与 `61af0b81...` 为 trace ID 示例。"),
        ("### Access the contract in daml shell", "### 在 daml shell 访问合约"),
        ("Open `daml shell` to query for the created contract. In a new terminal window, from the `quickstart/` directory run `make shell`",
         "新终端在 `quickstart/` 运行 `make shell` 打开 daml shell 查询合约。"),
        ("Query the `AppInstallRequest` contract:", "查询 `AppInstallRequest`："),
        ("Use the displayed portion of the contract ID to display the contract details.",
         "用显示的合约 ID 片段查看详情。"),
        ("In `daml shell` run the command contract followed by your unique Contract ID. In this case: `contract 0044e9b` until there are no other contract options. Press tab to complete the contract ID and enter to see the contract details.",
         "在 daml shell 运行 `contract <ID>`，可用 Tab 补全。"),
        ("Copy and save the contract ID to a new `INSTALL_REQ_CID` variable in the previous working terminal.",
         "将合约 ID 保存为 `INSTALL_REQ_CID`。"),
        ("Get the provider user token as a password grant for party rights.", "用 password grant 获取提供方用户令牌。"),
        ("Exercise the Accept choice on the first contract:", "对首个合约行使 Accept choice："),
        ("SUCCESS looks like `{\"updateId\":\"1220064a62356625ab7338564daedd21487749a7fcd21ad1d3a659b9131e9aadc246\",\"completionOffset\":109}%`",
         "成功类似 `{\"updateId\":\"...\",\"completionOffset\":109}`"),
        ("You can exercise the accept choice exactly once. After that you will receive an error because the contract has been accepted.",
         "Accept choice 只能行使一次，之后合约已接受会报错。"),
        ("Check if `app-provider` user exists", "检查 `app-provider` 用户是否存在"),
        ("If the `app-provider` user exists, get the party and verify it's set (if it fails review the previous steps):",
         "若存在则获取 party 并验证（失败请回顾前面步骤）："),
        ("The `APP_PROVIDER_USER_ID` should equal the \"id\" value.", "`APP_PROVIDER_USER_ID` 应等于 \"id\" 值。"),
        ("You may verify that all of your variables are set:", "可验证变量已设置："),
        ("A valid token shows the provider token meta data.", "有效令牌显示提供方元数据。"),
        ("An invalid token may show \"a security-sensitive error has been received\"",
         "无效令牌可能显示 security-sensitive error"),
        ("If needed, regenerate the session and then check that the token is valid, again.", "必要时重新生成会话并再次验证。"),
        ("If you see an error \"Contract could not be found with id then you have assigned an incorrect contract ID to a contractId variable.",
         "若报 Contract could not be found，说明 contractId 变量不正确。"),
        ("Success returns a new updateId and completionOffset.", "成功返回新 updateId 与 completionOffset。"),
        ("Return to `daml shell` to get the License contract ID.", "回到 daml shell 获取 License 合约 ID。"),
        ("Copy the complete contract ID and return to the previous working terminal.", "复制完整合约 ID 回到工作终端。"),
        ("If you receive a \"security-sensitive error has been received\" then renew the token as before.",
         "若遇 security-sensitive error 请按前述刷新令牌。"),
        ("As a sanity check you may preemptively renew the token.", "可先刷新令牌以防过期。"),
        ("You have 15 minutes to allocate tokens and 30 minutes to complete the renewal request.",
         "须在 15 分钟内分配代币，30 分钟内完成续期请求。"),
        ("A backend service is required for this step because the DSO and the user exchange information stored in `lockedAmulet`. This information is not available to the Provider and therefore cannot be accessed via the daml shell.",
         "此步骤需后端：DSO 与用户交换的 `lockedAmulet` 信息对提供方不可见，daml shell 无法获取。"),
        ("Success ends in a `licenseId`", "成功返回 `licenseId`"),
        ("After successful execution, return to daml shell and run a contract command using the new `licenseId` that was just returned to you.",
         "成功后回到 daml shell 用返回的 licenseId 运行 contract 命令。"),
        ("In the `Payload` field, notice that the `expiresAt` value is set for 30 days in the future.",
         "Payload 中 `expiresAt` 约为 30 天后。"),
        ("Congratulations! You've made a complete business operation in the Quickstart application using JSON API (with minimal help from the backend service to collect information not available in PQS for `complete-renewal`).",
         "恭喜！你已通过 JSON API 在 Quickstart 完成完整业务操作（`complete-renewal` 需后端补充 PQS 不可用信息）。"),
        ("The user must allocate 100 CC tokens to satisfy the payment.", "用户须分配 100 CC 完成付款。"),
        ("If the return shows \"\\<empty\\>\", wait a couple minutes and try again. (It can take up to 15 minutes). This is normal Canton Network behavior due to how the Participant Query Store (PQS) works. Before the holding, or any other on-ledger activity shows in the `daml shell`, the transaction must be processed on the ledger, PQS polls the participant for new events and updates its database, and after the sync completes the queries return the new data.",
         "若返回空，等待数分钟重试（最多约 15 分钟）；PQS 需先处理账本事件再同步到查询。"),
        ("The value in `amount` needs to be more than 100 to complete this step.", "此步骤 `amount` 须大于 100。"),
        ("In LocalNet, the Canton Wallet automatically replenishes tokens in each round. If your amount shows less than 100, then you most likely only need to wait a few minutes for the wallet to build up to a satisfactory amount.",
         "LocalNet 中 Canton 钱包每轮自动补充代币；不足 100 时通常稍等即可。"),
        ("Optional: If you'd like to view more details, call the Holding contract ID.", "可选：用 Holding 合约 ID 查看更多详情。"),
        ("Navigate to the Canton Wallet UI at [http://wallet.localhost:2000/allocations](http://wallet.localhost:2000/allocations)",
         "打开 [Canton 钱包 Allocations](http://wallet.localhost:2000/allocations)"),
        ("Log in as `app-user` with password `abc123`", "以 app-user / abc123 登录"),
        ("In the demo, the allocation was completed for you via backend processes in the web app. Now, we need to fill out the allocation request manually",
         "演示中 Web 应用后端代为完成分配；现需手动填写分配请求。"),
        ("You need to manually create an allocation for the daml shell allocation contract even if the UI shows an allocation request.",
         "即使 UI 已有请求，仍须为 daml shell 中的 allocation 合约手动创建分配。"),
        ("Use the `Payload` metadata mentioned above to fill in all the fields surrounded by red.",
         "用上文 Payload 元数据填写标红字段。"),
        ("Do NOT wrap values in quotes. Canton Wallet adds escaped quotes.", "值勿加引号；Canton 钱包会转义引号。"),
        ("Both key value pairs go in both meta options.", "两对键值须分别填入两个 meta。"),
        ("To find the necessary information, look at the LicenseRenewalRequest contract `payload` field in daml shell.",
         "所需信息见 daml shell 中 LicenseRenewalRequest 的 payload。"),
        ("For the times `Requested At`, `Settle before`, and `Allocate before`, you will need to manually enter a \".\" before the \"Z\" followed by six (6) \"0\"s.",
         "时间字段须在 Z 前加 `.` 及六个 0，例如 `2025-10-29T20:38:16.000000Z`。"),
        ("Send the request once all information is complete.", "信息填完后发送请求。"),
        ("Tokens automatically expire over time. This is a security measure and no fault of your own if you experience such errors.",
         "令牌会过期，属安全措施。"),
        ("Double check that the license renewal request, allocation , and license contract IDs are different. You may verify contract ID variables with values in `daml shell`.",
         "确认续期请求、allocation、许可合约 ID 互不相同；可与 daml shell 对照。"),
        ("(2901, 3901, 4901): Canton Ledger API access", "（2901、3901、4901）：Canton Ledger API"),
        ("(2902, 3902, 4902): system administration", "（2902、3902、4902）：系统管理"),
        ("You can find the health check endpoints for each validator in `quickstart/docker/modules/localnet/docker/splice/health-check.sh`.",
         "健康检查端点见 `quickstart/docker/modules/localnet/docker/splice/health-check.sh`。"),
        ("Empty responses indicate healthy services.", "空响应表示健康。"),
    ]
    p.extend(COMMON)
    out = apply(en, "使用 JSON Ledger API", "使用 JSON Ledger API", h, p)
    (BODY / "appdev-quickstart-json-api.zh.txt").write_text(out, encoding="utf-8")
    print("json-api", len(out))


def main():
    deploy()
    running_demo()
    observability()
    json_api()
    print("batch9 big translate done")


if __name__ == "__main__":
    main()

